version: '3.3'
services:
 postgres-chat:
  image: postgres:16.2-alpine
  container_name: depository-db
  environment:
   POSTGRES_DB: "depository"
   POSTGRES_USER: "postgres"
   POSTGRES_PASSWORD: "qwerty12345"
   PGDATA: "/home/vit/Документы/go/pg/pgdata"
  volumes:
   - ./data:/home/vit/Документы/go/pg/
   # Указываем, куда можно примонтировать папку
   # с данными на локальную хост машину.
   # Таким образом данные будет проще забекапить или перенести,
   # а так же они не удалятся если удалить контейнер.
  ports:
   - "5433:5432"